/**
 * Laptop Duhok — مفاتيح النصوص القابلة للتحرير من لوحة الإدارة
 * كل مفتاح: [ "i18n.key", "معرف المجموعة", "عنوان الحقل" ]
 */
window.LD_CMS_KEY_LIST = [
  ["meta.title", "seo", "عنوان الصفحة (المتصفح)"],
  ["meta.description", "seo", "وصف الميتا (بحث)"],
  ["meta.keywords", "seo", "كلمات مفتاحية"],
  ["meta.og_title", "seo", "Open Graph — العنوان"],
  ["meta.og_description", "seo", "Open Graph — الوصف"],
  ["a11y.skip", "nav", "رابط تخطي المحتوى"],
  ["nav.about", "nav", "قائمة: من نحن"],
  ["nav.services", "nav", "قائمة: الخدمات"],
  ["nav.portfolio", "nav", "قائمة: معرض الأعمال"],
  ["nav.process", "nav", "قائمة: آلية العمل"],
  ["nav.pricing", "nav", "قائمة: الأسعار"],
  ["nav.faq", "nav", "قائمة: الأسئلة"],
  ["nav.contact", "nav", "قائمة: تواصل"],
  ["header.service", "header", "تسمية هاتف الرأس"],
  ["contact.phone_href", "contact", "رابط الهاتف (tel:…)"],
  ["contact.phone_display", "contact", "عرض رقم الهاتف"],
  ["contact.email_href", "contact", "رابط البريد (mailto:…)"],
  ["contact.email_text", "contact", "نص البريد المعروض"],
  ["hero.kicker", "hero", "Hero — سطر علوي"],
  ["hero.title1", "hero", "Hero — شريحة 1 عنوان"],
  ["hero.desc1", "hero", "Hero — شريحة 1 وصف"],
  ["hero.title2", "hero", "Hero — شريحة 2 عنوان"],
  ["hero.desc2", "hero", "Hero — شريحة 2 وصف"],
  ["hero.title3", "hero", "Hero — شريحة 3 عنوان"],
  ["hero.desc3", "hero", "Hero — شريحة 3 وصف"],
  ["hero.cta", "hero", "Hero — زر رئيسي"],
  ["hero.cta_secondary", "hero", "Hero — زر ثانوي"],
  ["stats.digital_label", "stats", "عنوان مخفي للشريط الرقمي"],
  ["stats.digital_caption", "stats", "وصف تحت العداد الكبير"],
  ["stats.heading", "stats", "عنوان قسم الأرقام"],
  ["stats.lead", "stats", "مقدمة قسم الأرقام"],
  ["stats.s1_label", "stats", "تسمية عمود 1"],
  ["stats.s1_desc", "stats", "وصف عمود 1"],
  ["stats.s2_label", "stats", "تسمية عمود 2"],
  ["stats.s2_desc", "stats", "وصف عمود 2"],
  ["stats.s3_label", "stats", "تسمية عمود 3"],
  ["stats.s3_desc", "stats", "وصف عمود 3"],
  ["stats.s4_label", "stats", "تسمية عمود 4"],
  ["stats.s4_desc", "stats", "وصف عمود 4"],
  ["services.heading", "services", "عنوان الخدمات"],
  ["services.lead", "services", "مقدمة الخدمات"],
  ["page_services.read_full", "services", "رابط النسخة التفصيلية"],
  ["services.c1_title", "services", "بطاقة 1 عنوان"],
  ["services.c1_desc", "services", "بطاقة 1 وصف"],
  ["services.c1_i1", "services", "بطاقة 1 نقطة 1"],
  ["services.c1_i2", "services", "بطاقة 1 نقطة 2"],
  ["services.c2_title", "services", "بطاقة 2 عنوان"],
  ["services.c2_desc", "services", "بطاقة 2 وصف"],
  ["services.c2_i1", "services", "بطاقة 2 نقطة 1"],
  ["services.c2_i2", "services", "بطاقة 2 نقطة 2"],
  ["services.c3_title", "services", "بطاقة 3 عنوان"],
  ["services.c3_desc", "services", "بطاقة 3 وصف"],
  ["services.c3_i1", "services", "بطاقة 3 نقطة 1"],
  ["services.c3_i2", "services", "بطاقة 3 نقطة 2"],
  ["services.c4_title", "services", "بطاقة 4 عنوان"],
  ["services.c4_desc", "services", "بطاقة 4 وصف"],
  ["services.c4_i1", "services", "بطاقة 4 نقطة 1"],
  ["services.c4_i2", "services", "بطاقة 4 نقطة 2"],
  ["process.heading", "process", "عنوان آلية العمل"],
  ["process.lead", "process", "مقدمة آلية العمل"],
  ["process.s1_title", "process", "خطوة 1 عنوان"],
  ["process.s1_desc", "process", "خطوة 1 وصف"],
  ["process.s2_title", "process", "خطوة 2 عنوان"],
  ["process.s2_desc", "process", "خطوة 2 وصف"],
  ["process.s3_title", "process", "خطوة 3 عنوان"],
  ["process.s3_desc", "process", "خطوة 3 وصف"],
  ["process.s4_title", "process", "خطوة 4 عنوان"],
  ["process.s4_desc", "process", "خطوة 4 وصف"],
  ["portfolio.heading", "portfolio", "عنوان المعرض"],
  ["portfolio.lead", "portfolio", "مقدمة المعرض"],
  ["portfolio.filter_all", "portfolio", "فلتر الكل"],
  ["portfolio.filter_web", "portfolio", "فلتر مواقع"],
  ["portfolio.filter_app", "portfolio", "فلتر تطبيقات"],
  ["portfolio.filter_brand", "portfolio", "فلتر هوية"],
  ["portfolio.tag_web", "portfolio", "وسم موقع"],
  ["portfolio.tag_app", "portfolio", "وسم تطبيق"],
  ["portfolio.tag_brand", "portfolio", "وسم هوية"],
  ["portfolio.p1_title", "portfolio", "مشروع 1 عنوان"],
  ["portfolio.p1_meta", "portfolio", "مشروع 1 تقنيات"],
  ["portfolio.p1_desc", "portfolio", "مشروع 1 وصف"],
  ["portfolio.p2_title", "portfolio", "مشروع 2 عنوان"],
  ["portfolio.p2_meta", "portfolio", "مشروع 2 تقنيات"],
  ["portfolio.p2_desc", "portfolio", "مشروع 2 وصف"],
  ["portfolio.p3_title", "portfolio", "مشروع 3 عنوان"],
  ["portfolio.p3_meta", "portfolio", "مشروع 3 تقنيات"],
  ["portfolio.p3_desc", "portfolio", "مشروع 3 وصف"],
  ["portfolio.p4_title", "portfolio", "مشروع 4 عنوان"],
  ["portfolio.p4_meta", "portfolio", "مشروع 4 تقنيات"],
  ["portfolio.p4_desc", "portfolio", "مشروع 4 وصف"],
  ["portfolio.view", "portfolio", "رابط تفاصيل المشروع"],
  ["pricing.heading", "pricing", "عنوان الأسعار"],
  ["pricing.lead", "pricing", "مقدمة الأسعار"],
  ["pricing.col_service", "pricing", "رأس عمود الخدمة"],
  ["pricing.col_scope", "pricing", "رأس عمود النطاق"],
  ["pricing.col_price", "pricing", "رأس عمود السعر"],
  ["pricing.r1_name", "pricing", "صف 1 اسم الخدمة"],
  ["pricing.r1_scope", "pricing", "صف 1 النطاق"],
  ["pricing.r1_price", "pricing", "صف 1 السعر"],
  ["pricing.r2_name", "pricing", "صف 2 اسم الخدمة"],
  ["pricing.r2_scope", "pricing", "صف 2 النطاق"],
  ["pricing.r2_price", "pricing", "صف 2 السعر"],
  ["pricing.r3_name", "pricing", "صف 3 اسم الخدمة"],
  ["pricing.r3_scope", "pricing", "صف 3 النطاق"],
  ["pricing.r3_price", "pricing", "صف 3 السعر"],
  ["pricing.r4_name", "pricing", "صف 4 اسم الخدمة"],
  ["pricing.r4_scope", "pricing", "صف 4 النطاق"],
  ["pricing.r4_price", "pricing", "صف 4 السعر"],
  ["pricing.note", "pricing", "ملاحظة أسفل الجدول"],
  ["about.heading", "about", "من نحن — عنوان"],
  ["about.text", "about", "من نحن — فقرة 1"],
  ["about.text2", "about", "من نحن — فقرة 2"],
  ["about.b1", "about", "نقطة 1"],
  ["about.b2", "about", "نقطة 2"],
  ["about.b3", "about", "نقطة 3"],
  ["about.v1_title", "about", "قيمة 1 عنوان"],
  ["about.v1_desc", "about", "قيمة 1 وصف"],
  ["about.v2_title", "about", "قيمة 2 عنوان"],
  ["about.v2_desc", "about", "قيمة 2 وصف"],
  ["about.v3_title", "about", "قيمة 3 عنوان"],
  ["about.v3_desc", "about", "قيمة 3 وصف"],
  ["about.testimonials", "about", "عنوان الشهادات"],
  ["about.t1", "about", "شهادة 1"],
  ["about.t1_author", "about", "شهادة 1 مصدر"],
  ["about.t2", "about", "شهادة 2"],
  ["about.t2_author", "about", "شهادة 2 مصدر"],
  ["faq.heading", "faq", "عنوان الأسئلة"],
  ["faq.lead", "faq", "مقدمة الأسئلة"],
  ["faq.q1", "faq", "سؤال 1"],
  ["faq.a1", "faq", "جواب 1"],
  ["faq.q2", "faq", "سؤال 2"],
  ["faq.a2", "faq", "جواب 2"],
  ["faq.q3", "faq", "سؤال 3"],
  ["faq.a3", "faq", "جواب 3"],
  ["faq.q4", "faq", "سؤال 4"],
  ["faq.a4", "faq", "جواب 4"],
  ["faq.q5", "faq", "سؤال 5"],
  ["faq.a5", "faq", "جواب 5"],
  ["contact.heading", "contact", "تواصل — عنوان"],
  ["contact.lead", "contact", "تواصل — مقدمة"],
  ["contact.name", "contact", "تسمية حقل الاسم"],
  ["contact.name_ph", "contact", "placeholder الاسم"],
  ["contact.email", "contact", "تسمية البريد"],
  ["contact.email_ph", "contact", "placeholder البريد"],
  ["contact.message", "contact", "تسمية الرسالة"],
  ["contact.message_ph", "contact", "placeholder الرسالة"],
  ["contact.submit", "contact", "زر الإرسال"],
  ["contact.visit", "contact", "بطاقة زيارة — عنوان"],
  ["contact.address", "contact", "العنوان"],
  ["contact.hours_label", "contact", "تسمية ساعات الرد"],
  ["contact.hours_val", "contact", "قيمة ساعات الرد"],
  ["contact.note", "contact", "ملاحظة الطوارئ"],
  ["footer.tagline", "footer", "شعار الفوتر"],
  ["footer.quick", "footer", "عنوان روابط سريعة"],
  ["footer.legal", "footer", "عنوان معلومات"],
  ["footer.link_faq", "footer", "رابط أسئلة شائعة"],
  ["footer.link_process", "footer", "رابط آلية العمل"],
  ["footer.link_about", "footer", "رابط من نحن"],
  ["fab.text", "footer", "زر عائم — نص"],
  ["fab.aria", "footer", "زر عائم — تسمية إتاحة"],
];

window.LD_CMS_GROUP_LABELS = {
  seo: "SEO والعناوين",
  nav: "القائمة",
  header: "رأس الصفحة",
  hero: "الواجهة البطولية",
  stats: "قسم الأرقام",
  services: "الخدمات",
  process: "آلية العمل",
  portfolio: "معرض الأعمال",
  pricing: "الأسعار",
  about: "من نحن",
  faq: "الأسئلة الشائعة",
  contact: "التواصل وبيانات الاتصال",
  footer: "الفوتر والزر العائم",
};
