/**
 * كتالوج افتراضي للمتجر — يُستخدم إذا لم يُنفَّذ shop.sql أو لا توجد منتجات منشورة في Supabase.
 * عند وجود بيانات في الجداول، يحمّلها js/shop-loader.js ويستبدل هذا القائمة.
 */
(function () {
  window.LD_SHOP_CATEGORIES = [
    { id: "all", icon: "grid" },
    { id: "cashier", icon: "monitor" },
    { id: "laptops", icon: "laptop" },
    { id: "paper", icon: "layers" },
    { id: "peripherals", icon: "keyboard" },
    { id: "accessories", icon: "package" },
  ];

  window.LD_SHOP_PRODUCTS = [
    {
      id: "pos-zen",
      category: "cashier",
      name_ar: "نقطة بيع Zen — شاشة لمس",
      name_ckb: "خاڵی فرۆشتنی Zen",
      desc_ar: "نظام كاشير متكامل مع طابعة حرارية ودرج نقود — مناسب للمحلات والصيدليات.",
      desc_ckb: "سیستەمی کاشێر لەگەڵ چاپکەر و قاپی پارە.",
      price: 1850000,
      badge_ar: "الأكثر طلباً",
      badge_ckb: "زۆر داواکراو",
      badge_bad: "پتر داواکری",
    },
    {
      id: "pos-compact",
      category: "cashier",
      name_ar: "كاشير مدمج صغير",
      name_ckb: "کاشێری بچووک",
      desc_ar: "حجم مضغوط، واجهة سريعة، دعم باركود وعدة طرق دفع.",
      desc_ckb: "قەبارە بچووک، ڕووکاری خێرا، بارکۆد.",
      price: 980000,
    },
    {
      id: "lap-pro",
      category: "laptops",
      name_ar: "لابتوب Pro 15\" — معالج حديث",
      name_ckb: "لاپتۆپ Pro ١٥",
      desc_ar: "مناسب للتصميم والبرمجة — ذاكرة عالية وSSD سريع.",
      desc_ckb: "بۆ دیزاین و بەرنامەسازی.",
      price: 1250000,
      badge_ar: "جديد",
      badge_ckb: "نوێ",
      badge_bad: "نوی",
    },
    {
      id: "lap-office",
      category: "laptops",
      name_ar: "لابتوب مكتب — فئة اقتصادية",
      name_ckb: "لاپتۆپی ئۆفیس",
      desc_ar: "أداء موثوق للمهام اليومية والتصفح ووورد/إكسل.",
      desc_ckb: "بۆ کارەکانی ڕۆژانە.",
      price: 650000,
    },
    {
      id: "lap-gaming",
      category: "laptops",
      name_ar: "لابتوب ألعاب — شاشة 144Hz",
      name_ckb: "لاپتۆپی یاری",
      desc_ar: "كرت شاشة قوي، تبريد محسّن — للمحتوى الثقيل.",
      desc_ckb: "گرافیک بەهێز.",
      price: 2100000,
    },
    {
      id: "paper-a4",
      category: "paper",
      name_ar: "ورق A4 — علبة 5 رزم",
      name_ckb: "کاغەزی A4",
      desc_ar: "وزن 80 غرام، أبيض عالي الجودة للطباعة اليومية.",
      desc_ckb: "کاغەزی سپی بۆ چاپ.",
      price: 28000,
    },
    {
      id: "paper-thermal",
      category: "paper",
      name_ar: "رول حراري 80مم — عبوة 10",
      name_ckb: "ڕۆڵی گەرمی",
      desc_ar: "للطابعات الحرارية في الكاشير والمطاعم.",
      desc_ckb: "بۆ چاپکەری گەرمی.",
      price: 45000,
    },
    {
      id: "kb-mechanical",
      category: "peripherals",
      name_ar: "كيبورد ميكانيكي — إضاءة RGB",
      name_ckb: "تەختەی میکانیکی",
      desc_ar: "مفاتيح دقيقة، عمر افتراضي طويل — مريح للكتابة الطويلة.",
      desc_ckb: "نەرم و درێژخایەن.",
      price: 185000,
    },
    {
      id: "mouse-ergo",
      category: "peripherals",
      name_ar: "ماوس لاسلكي — تصميم مريح",
      name_ckb: "ماوسی بێ وێنە",
      desc_ar: "استجابة سريعة، بطارية تدوم أسابيع.",
      desc_ckb: "خێرا و باتری درێژ.",
      price: 65000,
    },
    {
      id: "set-desk",
      category: "peripherals",
      name_ar: "طقم مكتب: كيبورد + ماوس",
      name_ckb: "کۆمەڵەی ئۆفیس",
      desc_ar: "حل متكامل بسعر مناسب للشركات الصغيرة.",
      desc_ckb: "نرخی گونجاو.",
      price: 95000,
    },
    {
      id: "usb-hub",
      category: "accessories",
      name_ar: "موزع USB-C — 7 منافذ",
      name_ckb: "هەب USB",
      desc_ar: "شحن سريع، قارئ كروت، HDMI — للمكاتب المتنقلة.",
      desc_ckb: "چەند پۆرت.",
      price: 72000,
    },
    {
      id: "bag-laptop",
      category: "accessories",
      name_ar: "حقيبة لابتوب 15–16 بوصة",
      name_ckb: "جانتا بۆ لاپتۆپ",
      desc_ar: "مبطّنة، مقاومة للماء الخفيف، جيب للشاحن.",
      desc_ckb: "ناوەرۆکی نەرم.",
      price: 85000,
    },
  ];
})();
